src/Momon/BackendBundle/Form/ProjectType.php
<?php

namespace Momon\BackendBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Netik\MediaBundle\Form\SimpleFileType;

class ProjectType extends AbstractType


{


    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('numOrder')
            ->add('url')
            ->add('banner', new SimpleFileType() )
            ->add('category')
            ->add('model')
            ->add('translations', 'a2lix_translations')
        ;
    }

    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Momon\BackendBundle\Entity\Project'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'momon_backendbundle_project';
    }


}

src/Momon/BackendBundle/Resources/views/Page/create.html.twig
{% import 'MediaBundle:Gallery:gallery.html.twig' as gallery %}
{% extends 'BackendBundle:Backend:base.html.twig' %}

{% block contenido -%}
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Crear Page
                <small>Añade un nuevo elemento al sistema</small>
            </h1>
            <ol class="breadcrumb">
                                <li><a href="{{ path('backend_page_index') }}">Pages</a></li>
                <li class="active">Crear Page</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            {% include 'BaseBundle:Base:flash.html.twig' -%}

            <div class="row">
                <div class="col-md-6">

                    <!-- Default box -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Crear Page</h3>
                            <div class="box-tools pull-right">
                                <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Esconder"><i class="fa fa-minus"></i></button>
                                <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Eliminar"><i class="fa fa-times"></i></button>
                            </div>
                        </div>

                        <div class="box-body">
                            {{ form(oForm, {'attr': {'id': 'page-create'}} ) }}
                        </div><!-- /.box-body -->

                        <div class="box-footer">
                            <a href="{{ path('backend_page_index') }}" class="btn btn-default">Cancelar</a>
                            <button type="submit" id="bSaveButton" class="btn btn-primary pull-right">Guardar</button>
                        </div>
                    </div><!-- /.box -->

                </div>
            </div>

        </section><!-- /.content -->

    </div><!-- /.content-wrapper -->
{% endblock %}


{% block javascripts -%}
    <script>
        $(document).ready(function() {
            $( "#bSaveButton" ).click(function() {
                $('#page-create' ).submit();
            });

            $(".textarea").wysihtml5({

                "toolbar": {
                    "image": false,
                    "html" : true,
                    "blockquote": false,
                    "link": false
                },
                "locale": 'es-ES'

            });

        });
    </script>
{% endblock %}

src/Momon/BackendBundle/Resources/views/Page/edit.html.twig
{% import 'MediaBundle:Gallery:gallery.html.twig' as gallery %}
{% import 'MediaBundle:Folder:folder.html.twig' as folder %}
{% extends 'BackendBundle:Backend:base.html.twig' %}


{% block contenido -%}

    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Editar Page
                <small>Editar información del sistema</small>
            </h1>
            <ol class="breadcrumb">
                                <li><a href="{{ path('backend_page_index') }}">Pages</a></li>
                <li class="active">Editar Page</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            {% include 'BaseBundle:Base:flash.html.twig' -%}

            <div class="row">
                <div class="col-md-6">

                    <!-- Default box -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Editar Page</h3>
                            <div class="box-tools pull-right">
                                <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Esconder"><i class="fa fa-minus"></i></button>
                                <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Eliminar"><i class="fa fa-times"></i></button>
                            </div>
                        </div>

                        <div class="box-body">
                            {{ form(oForm, {'attr': {'id': 'page-edit'}} ) }}
                        </div><!-- /.box-body -->

                        <div class="box-footer">
                            <a href="{{ path('backend_page_index') }}" class="btn btn-default">Cancelar</a>
                            <button type="submit" id="bSaveButton" class="btn btn-primary pull-right">Guardar</button>
                        </div>
                    </div><!-- /.box -->

                </div>
                <div class="col-md-6">
                    {{ gallery.render(oPage) }}
                    {{ folder.render(oPage) }}
                </div>
            </div>

        </section><!-- /.content -->

    </div><!-- /.content-wrapper -->

{% endblock %}

{% block javascripts -%}
    <script>
        $(document).ready(function() {
            $( "#bSaveButton" ).click(function() {
                $('#page-edit' ).submit();
            });

            $(".textarea").wysihtml5({

                "toolbar": {
                    "image": true,
                    "html" : true,
                    "blockquote": true,
                    "link": true
                },
                "locale": 'es-ES'

            });
        });
    </script>

    {{ gallery.javascripts(oPage) }}
    {{ folder.javascripts(oPage) }}

{% endblock %}

src/Momon/BackendBundle/Resources/views/Page/index.html.twig
{% import 'MediaBundle:Gallery:gallery.html.twig' as gallery %}
{% extends 'BackendBundle:Backend:base.html.twig' %}


{% block contenido -%}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Pages
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
                        <li class="active">Pruebas</li>
        </ol>
    </section>



    <!-- Main content -->
    <section class="content">

        {% include 'BaseBundle:Base:flash.html.twig' -%}

        <!-- Default box -->
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title">Listado de Pages</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                </div>
            </div>

            <div class="box-body">

                <table id="tabla-listado" class="table table-hover">
                    <thead>
                    <tr>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Slug</th>
                            <th>Título</th>
                            <th>Nomon Culture</th>
                            <th>Orden</th>
                            <th>Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for oPage in aPages %}
                        <tr>
                                <td>
                                    <a href="{{ path('backend_page_view', { nPageId: oPage.id }) }}">{{  oPage.id }}</a>
                                </td>
                                <td>
                                    {{  oPage.name }}
                                </td>
                                <td>
                                    {{  oPage.slug }}
                                </td>
                                <td>
                                    {{  oPage.title }}
                                </td>
                                <td>
                                    {{  oPage.numWorld }}
                                </td>
                                <td>
                                    {{  oPage.numOrder }}
                                </td>
                                <td>
    
        <a href="{{ path('backend_page_view', { 'nPageId':  oPage.id }) }}" class="btn  btn-success  btn-xs"> <i class="fa fa-eye"></i> Ver</a>

    
    
    
    
    
        <a href="{{ path('backend_page_edit', { 'nPageId':  oPage.id }) }}" class="btn  btn-warning  btn-xs"><i class="fa fa-pencil"></i> Editar</a>

    
    
    
    
    
        <a href="#" url="{{ path('backend_page_delete', { 'nPageId':  oPage.id }) }}" class="btn  btn-danger  btn-xs delete-button"><i class="fa fa-times"></i> Eliminar</a>

    



                                </td>
                        </tr>

                        {% endfor %}

                    </tbody>
                </table>

            </div><!-- /.box-body -->

        </div><!-- /.box -->

    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar</h4>
            </div>
            <div class="modal-body">
                ¿Está seguro que desea eliminar el objeto?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <a type="button" class="btn btn-danger" id="confirm-button" href="#">Eliminar</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function() {

            $( ".delete-button" ).click(function() {
                $('#delete_confirm').modal();
                $("#confirm-button").attr( "href", $(this).attr('url') )
            });

            $('#tabla-listado').DataTable({
                responsive: true,
                language: {
                    "sProcessing":     "Procesando...",
                    "sLengthMenu":     "Mostrar _MENU_ registros",
                    "sZeroRecords":    "No se encontraron resultados",
                    "sEmptyTable":     "Ningún dato disponible en esta tabla",
                    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":    "",
                    "sSearch":         "Buscar:",
                    "sUrl":            "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     "Último",
                        "sNext":     "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });

        });
    </script>
{% endblock %}

src/Momon/BackendBundle/Resources/views/Page/view.html.twig
{% import 'MediaBundle:Gallery:gallery.html.twig' as gallery %}
{% import 'MediaBundle:Folder:folder.html.twig' as folder %}
{% extends 'BackendBundle:Backend:base.html.twig' %}

{% block contenido -%}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Page
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
                        <li ><a href="{{ path('backend_page_index') }}">Pages</a></li>
            <li class="active">Ver Page</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        {% include 'BaseBundle:Base:flash.html.twig' -%}

        <div class="row">
            <div class="col-md-6">

                <!-- Default box -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ver Page</h3>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Esconder"><i class="fa fa-minus"></i></button>
                            <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Eliminar"><i class="fa fa-times"></i></button>
                        </div>
                    </div>

                    <div class="box-body">
                        {{ form(oForm, {'attr': {'id': 'page-view'}} ) }}
                    </div><!-- /.box-body -->

                    <div class="box-footer">
                        <a href="{{ path('backend_page_index') }}" class="btn btn-default">Volver al Listado</a>
                        <a href="{{ path('backend_page_edit', { 'nPageId':  oPage.id }) }}"  class="btn btn-primary pull-right">Editar</a>
                    </div>
                </div><!-- /.box -->

            </div>
            <div class="col-md-6">
                {{ gallery.render(oPage) }}
                {{ folder.render(oPage) }}
            </div>
        </div>

    </section><!-- /.content -->

</div><!-- /.content-wrapper -->
{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function() {
            $("#page-view input").attr('readonly', 'readonly');
            $("#page-view input").attr('disabled', 'disabled');
            $("#page-view textarea").prop('disabled', 'disabled');
            $("#page-view select").prop('disabled', 'disabled');

            $(".textarea").wysihtml5({

                "toolbar": {
                    "image": false,
                    "html" : true,
                    "blockquote": false,
                    "link": false
                },
                "locale": 'es-ES'

            });

        });
    </script>
    {{ gallery.javascripts(oPage) }}
    {{ folder.javascripts(oPage) }}
{% endblock %}